<a href="https://colab.research.google.com/github/vivekd16/Learning-Deep-Learning/blob/main/00_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.5.1+cu121'

In [4]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [20]:
tensor[0][0][0]

tensor(1)

In [25]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1929, 0.2463, 0.7530, 0.6567],
        [0.5236, 0.4026, 0.0108, 0.9717],
        [0.5988, 0.1434, 0.1228, 0.1045]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [26]:
# create a random image tensor with similar shape toa an image tensor
rnd_img_size_tensor=torch.rand(size=(224,224,3))
rnd_img_size_tensor

tensor([[[0.7816, 0.2279, 0.5280],
         [0.2980, 0.3115, 0.7767],
         [0.7719, 0.5168, 0.6027],
         ...,
         [0.6965, 0.0746, 0.1535],
         [0.6042, 0.9653, 0.8445],
         [0.0637, 0.6614, 0.1809]],

        [[0.5984, 0.9726, 0.7116],
         [0.6075, 0.6057, 0.7483],
         [0.0179, 0.7143, 0.4742],
         ...,
         [0.6445, 0.1705, 0.0769],
         [0.8180, 0.3300, 0.5508],
         [0.4141, 0.7901, 0.7453]],

        [[0.9346, 0.3570, 0.8332],
         [0.4164, 0.5900, 0.4790],
         [0.1802, 0.7240, 0.8300],
         ...,
         [0.0734, 0.0183, 0.5647],
         [0.7918, 0.4455, 0.6588],
         [0.5711, 0.8453, 0.9572]],

        ...,

        [[0.6373, 0.4503, 0.3443],
         [0.5470, 0.1018, 0.6628],
         [0.8398, 0.0763, 0.6791],
         ...,
         [0.8155, 0.6817, 0.9216],
         [0.4848, 0.4147, 0.2820],
         [0.6451, 0.1145, 0.5809]],

        [[0.7071, 0.7694, 0.2740],
         [0.6070, 0.2221, 0.7551],
         [0.

In [27]:
rnd_img_size_tensor.ndim,rnd_img_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [33]:
zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
one=torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
one.dtype

torch.float32

In [37]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# tensor like
zero=torch.zeros_like(torch.arange(0,10))
zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
tensor=torch.tensor([3.0,4.0,5.0],dtype=None,device=None,requires_grad=False)
tensor.dtype

torch.float32

In [42]:
fl16_tensor=tensor.type(torch.float16)
fl16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [43]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [44]:
tensor*10

tensor([10, 20, 30])

In [46]:
tensor

tensor([1, 2, 3])

In [47]:
torch.mul(tensor,10)

tensor([10, 20, 30])