<a href="https://colab.research.google.com/github/vivekd16/Deep-Learning/blob/main/00_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import torch
torch.__version__

'2.5.1+cu124'

In [76]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [77]:
scalar.ndim

0

In [78]:
scalar.item()

7

In [79]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [80]:
vector.ndim

1

In [81]:
vector.shape

torch.Size([2])

In [82]:
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [83]:
matrix.ndim

2

In [84]:
matrix[1]

tensor([ 9, 10])

In [85]:
matrix.shape

torch.Size([2, 2])

In [86]:
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [87]:
tensor.ndim

3

In [88]:
tensor.shape

torch.Size([1, 3, 3])

In [89]:
tensor[0][0][0]

tensor(1)

In [90]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [91]:
random_tensor.ndim

2

In [92]:
random_tensor.shape

torch.Size([3, 4])

In [93]:
# create a random image tensor with similar shape toa an image tensor
rnd_img_size_tensor=torch.rand(size=(224,224,3))
rnd_img_size_tensor

tensor([[[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860],
         ...,
         [0.3421, 0.0172, 0.3031],
         [0.6576, 0.9813, 0.5840],
         [0.9902, 0.5978, 0.7888]],

        [[0.9008, 0.9180, 0.2201],
         [0.9597, 0.8029, 0.2662],
         [0.2614, 0.0806, 0.6256],
         ...,
         [0.3568, 0.1704, 0.6172],
         [0.0231, 0.6317, 0.7472],
         [0.0614, 0.1727, 0.1405]],

        [[0.9203, 0.9251, 0.5313],
         [0.9694, 0.3328, 0.0146],
         [0.6746, 0.6771, 0.9902],
         ...,
         [0.8345, 0.2273, 0.2865],
         [0.3940, 0.1418, 0.3650],
         [0.0908, 0.6902, 0.8538]],

        ...,

        [[0.5521, 0.6004, 0.1658],
         [0.1479, 0.8327, 0.2563],
         [0.1063, 0.4770, 0.2286],
         ...,
         [0.1551, 0.7881, 0.3759],
         [0.7442, 0.8621, 0.7548],
         [0.6381, 0.0106, 0.0893]],

        [[0.6170, 0.3402, 0.8306],
         [0.0705, 0.2111, 0.6203],
         [0.

In [94]:
rnd_img_size_tensor.ndim,rnd_img_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [95]:
zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [96]:
one=torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
one.dtype

torch.float32

In [98]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# tensor like
zero=torch.zeros_like(torch.arange(0,10))
zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [100]:
tensor=torch.tensor([3.0,4.0,5.0],dtype=None,device=None,requires_grad=False)
tensor.dtype

torch.float32

In [101]:
fl16_tensor=tensor.type(torch.float16)
fl16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [102]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [103]:
tensor*10

tensor([10, 20, 30])

In [104]:
tensor

tensor([1, 2, 3])

In [105]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [106]:
#element wise mul
tensor*tensor

tensor([1, 4, 9])

In [107]:
#matrix mul
torch.matmul(tensor,tensor)

tensor(14)

In [108]:
%%time
value =0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.29 ms, sys: 0 ns, total: 2.29 ms
Wall time: 2.73 ms


In [109]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 64 µs, sys: 5 µs, total: 69 µs
Wall time: 77.2 µs


tensor(14)

In [110]:
# inner dimension must match
#result will be in the outer dimension shape
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.7011, 1.1414],
        [0.9407, 0.7416]])

In [111]:
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])
# torch.matmul(tensor_A,tensor_B)
# #bwcause the inner dimensions are different

In [112]:
#transpose
tensor_B.T.shape,tensor_B.shape


(torch.Size([2, 3]), torch.Size([3, 2]))

In [113]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [114]:
#min
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [115]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [116]:
#max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [117]:
#mean
torch.mean(x.type(torch.float32))
#datattype error mean need float type

tensor(45.)

In [118]:
#sum
torch.sum(x)

tensor(450)

In [119]:
x.argmin() #it returns the position of minimum in tensor

tensor(0)

In [120]:
x.argmax() #it returns the position of maximum in tensor

tensor(9)

In [121]:
#reshape
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [122]:
x_reshape=x.reshape(9,1)
x_reshape.shape,x_reshape

(torch.Size([9, 1]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [123]:
z=x.view(1,9)
z ,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [124]:
z[:,0]=5 #view carry the same memory address as the original tensor
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [125]:
#stack
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [126]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [127]:
x=torch.zeros(2,1,2,1,2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [128]:
y=torch.squeeze(x)
y.shape

torch.Size([2, 2, 2])

In [129]:
y,x

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]))

In [130]:
y=torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [131]:
y=torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [132]:
y


tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [133]:
x_reshape

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [134]:
x_squeeze=x_reshape.squeeze()
x_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [135]:
x_un=x_squeeze.unsqueeze(dim=0)
x_un.shape

torch.Size([1, 9])

In [136]:
x_o=torch.rand(size=(224,224,3))
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [137]:
x_p=x_o.permute(2,0,1) #permute change the shape or dimensions
x_p

tensor([[[1.3361e-01, 8.4745e-01, 4.5634e-01,  ..., 9.4231e-01,
          3.3080e-01, 1.2548e-01],
         [2.9286e-01, 5.1096e-01, 7.0275e-01,  ..., 7.7647e-01,
          1.6536e-02, 4.8083e-01],
         [1.8413e-01, 1.0416e-01, 4.4445e-02,  ..., 4.8183e-01,
          1.7475e-01, 7.9133e-02],
         ...,
         [8.8207e-01, 3.7006e-02, 9.1918e-01,  ..., 3.8510e-01,
          3.9180e-01, 2.5808e-01],
         [2.5540e-01, 9.7798e-01, 2.4298e-01,  ..., 2.9085e-01,
          5.1393e-01, 3.0401e-01],
         [2.1134e-02, 9.2047e-04, 2.0201e-01,  ..., 8.2232e-01,
          2.7461e-01, 6.4495e-01]],

        [[9.6661e-01, 8.9878e-01, 9.7194e-01,  ..., 8.7603e-01,
          6.4555e-02, 5.7870e-01],
         [6.5032e-01, 7.8809e-01, 7.1442e-02,  ..., 1.5217e-01,
          2.1086e-01, 9.3513e-01],
         [2.2169e-01, 5.7817e-01, 6.6294e-01,  ..., 2.6818e-01,
          5.7876e-01, 3.4279e-01],
         ...,
         [9.7808e-01, 4.6565e-01, 3.9074e-01,  ..., 9.5717e-01,
          2.504

In [138]:
# indexing
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [139]:
x[0],x[0][0],x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [140]:
#tensor and numpy
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [141]:
#no change occurs in tensor  when we change the array
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [142]:
#tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor,numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [143]:
#no change occurs in array  when we change the tensor
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [144]:
#reporducbility
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
tensor_c=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
tensor_d=torch.rand(3,4)
print(tensor_c)
print(tensor_d)
print(tensor_c==tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [145]:
torch.cuda.is_available()

False

In [146]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu
